tap "aws/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask-versions"
brew "ack"
brew "aws-elasticbeanstalk"
brew "aws-sam-cli"
brew "awscli"
brew "brew-php-switcher"
brew "composer"
brew "cowsay"
brew "docker", link: false
brew "docker-compose", link: false
brew "git-flow"
brew "jq"
brew "lolcat"
brew "node", link: false
brew "now-cli"
brew "php@7.2", link: true
brew "tldr"
brew "watch"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
cask "1password-beta"
cask "1password-cli"
cask "alfred"
cask "appcleaner"
cask "daisydisk"
cask "iterm2"
cask "now"
cask "phpstorm"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "rectangle"
cask "slack"
cask "suspicious-package"
cask "tresorit"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"

mas "Xcode", id: 497799835 